e:
cd E:\zhouh\java-workspace\NJU-Parser\
java -Xmx30g -cp NJU-Parser0.6.jar edu.nju.nlp.main.RunSyntaxParse mode=train trainFile=.\data\CTB5\train.txt modelFile=.\data\CTB5\0.6\model\BS.model trainIters=30 beamSize=16 averageParams=true testFile=.\data\CTB5\testi.txt testResultFile=.\data\CTB5\0.6\result\BS.result 
cd e:\zhouh\java-workspace\windows_evalb
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result1 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail1
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result2 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail2
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result3 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail3
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result4 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail4
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result5 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail5
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result6 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail6
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result7 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail7
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result8 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail8
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result9 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail9
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result10 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail10
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result11 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail11
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result12 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail12
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result13 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail13
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result14 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail14
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result15 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail15
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result16 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail16
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result17 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail17
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result18 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail18
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result19 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail19
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result20 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail20
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result21 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail21
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result22 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail22
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result23 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail23
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result24 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail24
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result25 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail25
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result26 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail26
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result27 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail27
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result28 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail28
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result29 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail29
evalb.exe -p new.prm e:\zhouh\java-workspace\NJU-Parser\data\CTB5\testr.txt e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\BS.result30 > e:\zhouh\java-workspace\NJU-Parser\data\CTB5\0.6\result\detail\BS.detail30
